language: generic
sudo: required
services: true

before_install:
  - docker build -t julianakk/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true julianakk/react-test npm test

after_success:
  - docker build -t julianakk/multi-client ./client
  - docker build -t julianakk/multi-nginx ./nginx
  - docker build -t julianakk/multi-server ./server
  - docker build -t julianakk/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to docker hub
  - docker push julianakk/multi-client
  - docker push julianakk/multi-nginx
  - docker push julianakk/multi-server
  - docker push julianakk/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-central-1-351261961147
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY