sudo: required
services: true

before_install:
  - docker build -t julianakk/react-test -f .client/Dockerfile.dev ./client

script:
  - docker run -e CI=true julianakk/react-test npm test

after_success:
  - docker build -t julianakk/multi-client ./client
  - docker build -t julianakk/multi-client ./nginx
  - docker build -t julianakk/multi-client ./server
  - docker build -t julianakk/multi-client ./worker
  # Log in to docker CLI
  - docker login DOCKER_ID@DOCKER_PASSWORD
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to docker hub
  - docker push julianakk/multi-client
  - docker push julianakk/multi-nginx
  - docker push julianakk/multi-server
  - docker push julianakk/multi-worker